include:
- local: ".gitlab/ci/*.gitlab-ci.yml"

stages:
- prerequisites
- build
- dockerize
- deploy

workflow:
  rules:
    - if: $CI_SERVER_URL == "https://gitlab.notyouraverage.dev"
      when: always
    - when: never
