server:
  port: 8080
spring:
  docker:
    compose:
      enabled: false
  kafka:
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
    properties:
      sasl:
        mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
        jaas:
          config: ${KAFKA_SASL_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_AUTH_USERNAME} password=${KAFKA_AUTH_PASSWORD};}
