server:
  port: 8081
spring:
  application:
    name: kafka-data-processor
  docker:
    compose:
      enabled: false
      file: ./dependencies/kafka-data-processor/compose.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
  grpc:
    client:
      channels:
        name-service:
          address: ${GRPC_NAME_SERVICE_ENDPOINT:localhost:9092}
  threads:
    virtual:
      enabled: ${ENABLE_VIRTUAL_THREADS:true}

management:
  tracing:
    enabled: ${ENABLE_TRACES:true}
    sampling:
      probability: ${TRACES_SAMPLING_RATE:1.0}
  otlp:
    tracing:
      endpoint: ${OLTP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

project:
  ui-app:
    hosts: "*"
  kafka:
    requestTopic:
      name: IncomingRequests
      partitions: 8
      replicas: 1
    responseTopic:
      name: ProcessedResponses
      partitions: 8
      replicas: 1
