replicaCount: 1

namespace: spring-projects

nameOverride: kafka-data-processor
fullnameOverride: kafka-data-processor

imagePullSecrets:
  - name: spring-projects-registry-secret

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

service:
  port: 8080

podAnnotations:
  linkerd.io/inject: enabled

sealedSecrets:
  enabled: true
  name: &sealed-secret-name kafka-data-processor-secrets
  secrets:
    KAFKA_AUTH_PASSWORD: AgCxE113MM5SHFHYj2dJZNh2DYC8gC2k1eqy6vzdMkPr1wb4iR/7sGE+LrbH3M9FFBtp+BS7b4j+dMkKimkerTskKpxG1wDaDXHxjG/HoI9dyjIx/ncXJ0HF66Xa3SgtZQGdTy8dnZYWk/FNKXu/oQe+FzRlnII08fd2bb5YkMKCp9nCpFtVauUs+RkBM5RsHkGoAmAfCKu1Qp6Ao2ngeTtw0Q/H5FWI4HW4hR+RsaqAQ/WnVsJAq6G2DETpgaAm3LPfOznRSmAWS7t5WOQ//2bZytaV//H/kd0+/yKxEVfZnAyisAhbbXwY2reovB0vu6TDpiKDZsQ9uTHNJ45I8pNdfF6KKjVSCt4U3v5X1C44qOAjW/FvwAB4XezDFgzxz8xrmlKZiOUghEjjoww/vt/+8FYQ3z1kyivEUoWHJsZ9SZ0xU0oO91xmA6l3UnQy4qIRDma6nuEUEq7feYklfgGPSpz1JLf26SCktU9rR4KmXb9SL03yAGziwtFBc5+dRF0aDQwl6lpTghygqm99EPMVOPnzbEhKsv/eQSJQ+I6hsS8ltUeXMQG6ufwXmscbGLYuvba+PHWMQhvrE5Jz+rX5cpFZqdfYuFfYpTWF8arI+yEWV/uV0ON+4B2bewKavgmqeB0Lv5QOvP7d0Q7OrwWo/AadfQjPonyFLz9ZQcMpgJKTak9aY5dk/qyUP5mYy8wG/OtP3EpG9sMJHBjof6kBpYTYOxeOtYgKTx3W6ywecREq1amvKLry70kibP7xDDynHWONXfb2o2cifbPrdbiC
    KAFKA_AUTH_USERNAME: AgCUUrb/zTyd3tqnWlVEK2l1nXSNFLtTvKTa+wUpOqzusKWxAX9KxaYYChkXPtGSHRJsy+nI0bAFZTCC/J2Wem9Yex31VfLqU9qbvwTwxcy7u14eA0z2X6uEmxfxyFxM41jSw38Upv10eTqObFY1yYVq/ckSFr3Ic5j+JrcmlH3U9l9YgkXxOLeaHOgUJqd+tngKXFhM3JRJMIx4sXHk6Zurwqk2TrGmktwAll3DyL8xGK8Aiw+bEXZjMdZt+s7V8ZiWncYowYGMvp6xlCsUg2V9jVHXJ2kMpeCid4V7EO1yN5xKnjXjlH41nNlwKz5Q0K+Ko9GYaAo6JXzfcEvEQ4QUqOy6EcxkGlO67HRaYukp3HPZgmoUuc3o95W8Vjp4whpCYz4X10s3IfLbCFeVD5C+sRL65/1QnGM/cYdQjjcYyj7xjC2W9wd8oCjAxx7X1GMn1WQ7oUfbcqx9Wv8N3iPYhAJtrm2iZqUeZkvELeBXSAWbN/yQWg5vxmhjgGaQg0x5cgj4++cA94c0TkwVHLtg1juuPyY4YHcWUHYpoExeIInqCUP/HELFUhrBlHJK8sf3psGeRY0t4wUTDf1niu81ZuhLjJ7kjrAGw3SHimDxG6A0/nHJ15pWPA7khvyBFAChlHkOLi3ZeShg0ydAXVlHIu5IViIfWZTtXs9RUgb5GdUE+u/sFLyKSeTJGqQSfpD3iiXaEV3Lq4hH

environmentVariables:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: apache-kafka.kafka.svc.cluster.local:9092
  - name: ENABLE_VIRTUAL_THREADS
    value: "true"
  - name: ENABLE_TRACES
    value: "false"
  - name: SPRING_PROFILES_ACTIVE
    value: production
  - name: TRACES_SAMPLING_RATE
    value: "0.0"
  - name: OLTP_TRACING_ENDPOINT
    value: http://locahost
  - name: KAFKA_AUTH_USERNAME
    valueFrom:
      secretKeyRef:
        key: KAFKA_AUTH_USERNAME
        name: *sealed-secret-name
  - name: KAFKA_AUTH_PASSWORD
    valueFrom:
      secretKeyRef:
        key: KAFKA_AUTH_PASSWORD
        name: *sealed-secret-name
