replicaCount: 1

namespace: spring-projects

nameOverride: kafka-data-processor
fullnameOverride: kafka-data-processor

imagePullSecrets:
  - name: spring-projects-registry-secret

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

service:
  port: 8080

podAnnotations:
  linkerd.io/inject: enabled

sealedSecrets:
  enabled: true
  name: &sealed-secret-name kafka-data-processor-secrets
  secrets:
    KAFKA_AUTH_PASSWORD: "AgADcODvt217tGwWL3nsvDENrregSH3F7Jgki1GFGmUi1WmO5JkEb0ob5bJHckBpq2Wnk+LNINydlk6EKf0R5kMgs5CTWa6AAB2zzLnMnbdENVx2g2g3iN3xZCo80qGhT7KuDdHdX6oYaPeXMkED7xgKqPaJTTHeaW22Y5GTjk/GkP+3vRSyCsdgpu16j9EImHXGS3MmtZuThPY4mNUW9BHKZuuzhmrfesElKNGttjXxYnp0iymKUCHPvUkBNyC+vdo8gnIhwyInFMsqezqp5VfLV3ZUJRWt8I7STlqdw179qb5DSE5c/HIoC7OpoV1pyWxA2nn/E47jr70KCwH6Z0MhHz6U51FxfxX2oLkSs92gq6A2Q7BQ0/HWsnTtDK7FsfGUHjSLLovjgmodwhhWZzqyKsyxTc2+nnXNustg+DQOXEkuo8AuglOuv5ehPEPnHVs5xcMfpkKxcL3GZHxHZ/BMJjDLlbo7juXZ4YGKcDeSMZORmfL4GzUmUc9FSHMM2Dl5uPcZoQ1719BNAvSrlI4C4UfMXGHCjc1kHd3myIao1TFRjux4agW4V9TuzDvsGK6zJnBh6obrs+WwcRzeGMMiB68STyT6xjcONl6aTCdd25tPIA1enclzl/OJydFjp1h6OKibeS7mW+dwGJufprGSxKjRnAeS5rJRwMxPGRnvDCv1ecD4h042cLPQijl/a7RFhO4AmHJWnW8fjBUBX2vVREpduE3wS/0mA4ZBOB0AO0TkKwuRCgIHFSbFisdFQ2WtHK7S6bR6zY+sT0H7g1TG"
    KAFKA_AUTH_USERNAME: "AgBlpF8aaxPijVxg18wzBJ7dDXWjrGd7BWY/2cLc/30/TLivUSXpnCz1xqzADO94+yIMqWt8iKRjaxCDvluFfWEfKf91uLP7kRM08UaBGV6vQDUsD7Ww5iz+MGPyAw5whjg+k/DSJmpeM1gUkJKnms6YJnO2EllMY2Sjt1RX1SCzCpJ3eHbPHqZW3469zWmoiVXJZxBiBpSkruvKLSbOfujQOtDhPE7sOlkwEkdnSTNohGxHy8mpz0cPr8lc6Cwc9bjqwuOsss+dsaTkPbFykGA0YNvvKhaGeG7SIXsvzqFYAfzpkYRZBixVaskjRFmoniK9dZYdcDnvaL+XMGXUAoWCav/FCOWXlT7g4IUiCd83FWZlJOPk+223t1+5xNKxxHHEKuRzzHk6YDqBD6sWeEmGQIot2hIsDIt2L8LaKqvloJawm1xaOwhX+HAc5EkTrujYqKOhTI3fpOgxOKP+rKxM0Om87N8ldvtmE/O4kUrCbX6WWZtSpbKK74DO7nBuf7z0UJBRJIhIvOb5ZFZelqCCP3Ze2HIaP+0Q93fZMCLFog9aV4vVqVlyLjw7RClUNE3w2utahP+hAsVmU9k3iMNR/8+NBacdUnv+cjANjKuioLcNc9aJszv6uZcyFfVAA3RihemLfWVbfzjR9zhZv1hArg2ndyNuc5kcAQnSycdtRIRqmkWVhHpyXX9D5LqdmH3BPWlXUlKVhSkA"
    KAFKA_SASL_MECHANISM: "AgB3b0JbcN+ODXQwfrJErywyNrK4QzZhMNsYtH01DQKe+s7SxRIjmqF7HBsn3enYj1traYuzREh/991qC4i6R+fLbL5B/2IMzL9qJbNZBIKjbzZvhVTilWs+Uc39Tkg0Rlmj9INiENHxX1BytEiCuc9R+oPlJgTFCAouvPUcznzjnU2yo63IjORTXbAfgHJFISN0Im+MUy5YrkMHZhF/dbsjPuFZQWqSoJ9tf2VkDe8iqBSgBIKym4KTe4+d06BZm9doJeO22BmXj3Wgzhv7D3V1mxaWce8zfO0s+xrGxTHz+5CvNWfuMiqhW8yw4KZUwli90mV/f9YyX629luKY3a4schf2lg72r8o71pvCY/0lpLo4bKCgr6QuGWQa32C2Wl/OR0H6ueuNCvz/Fok5GORPc5bQxbKg2U9Xlp+5v2cK0CGHJLjeRwEgnzV5r6M39wK8+ZOzZsxs5faR15rhtDwxB6wNxOfW3dHrgR/SqiPbJCwBb0FSXciUWklDP4ov+ghKFAmdhjHV6xHLMKKpyx7RFPNqiRVZdLtyP6ISqRXg84SEPlXWib5Q3r4aMgXa2xbWR/UJwf70tPyQbguB92ZASfa6vb31AnX6Xl1fzHUhy0w7lP4kZbcH+8susDICL28D5VfmdDWTDUe5T2wGYoQuJKfIqzzzPKYkKX0ZxbqBZhrNN40mt4KFyYYaACB8P3hq8AOzkCj3UB8="

autoscaling:
  enabled: true
  type: "keda"
  keda:
    enabled: true
    maxReplicas: 16
    scalers:
      - type: "kafka"
        metadata:
          bootstrapServers: "apache-kafka.kafka.svc.cluster.local:9092"
          consumerGroup: "IncomingRequestListener"
          topic: "IncomingRequests"
          lagThreshold: "200"
        triggerAuth:
          secretTargetRef:
            - parameter: sasl
              name: *sealed-secret-name
              key: KAFKA_SASL_MECHANISM
            - parameter: password
              name: *sealed-secret-name
              key: KAFKA_AUTH_PASSWORD
            - parameter: username
              name: *sealed-secret-name
              key: KAFKA_AUTH_USERNAME

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: "monitoring"

environmentVariables:
  - name: GRPC_NAME_SERVICE_ENDPOINT
    value: grpc-stats-aggregator.spring-projects.svc.cluster.local:8080
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: apache-kafka.kafka.svc.cluster.local:9092
  - name: ENABLE_VIRTUAL_THREADS
    value: "true"
  - name: ENABLE_TRACES
    value: "false"
  - name: SPRING_PROFILES_ACTIVE
    value: production
  - name: TRACES_SAMPLING_RATE
    value: "0.0"
  - name: OLTP_TRACING_ENDPOINT
    value: http://locahost
  - name: KAFKA_AUTH_USERNAME
    valueFrom:
      secretKeyRef:
        key: KAFKA_AUTH_USERNAME
        name: *sealed-secret-name
  - name: KAFKA_AUTH_PASSWORD
    valueFrom:
      secretKeyRef:
        key: KAFKA_AUTH_PASSWORD
        name: *sealed-secret-name
