services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6
    restart: always
    ports:
      - "9094:9094"
      - "9093:9093"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,DOCKER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,DOCKER://host.docker.internal:9093,EXTERNAL://localhost:9094

  kafka-ui:
    container_name: kafka-ui
    image: kafbat/kafka-ui:latest
    ports:
      - 9095:8080
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME = local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS = kafka:9092

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
